Repository kubernetes-csi/external-provisioner, pull requests merged in 2018-11, with the labels that each got.

#163 rbac: fix kubectl validation error
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 Update log message for help debugging
  .gitignore
  pkg/controller/topology.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#135 Add Block volume support for CSI provisioner
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#174 Update dependencies to use external-snapshotter v1.0.0-rc4
  Gopkg.lock
  Gopkg.toml
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/Makefile
  vendor/github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/setup-csi-snapshotter.yaml
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/csi_handler.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/framework_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/snapshot_controller.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/snapshot_controller_base.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/snapshot_controller_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/snapshot_create_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/snapshot_delete_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/snapshot_ready_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#179 Use logging util
  Gopkg.lock
  Gopkg.toml
  pkg/controller/controller.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/OWNERS
  vendor/github.com/kubernetes-csi/csi-lib-utils/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-lib-utils/code-of-conduct.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/.gitignore
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest/csitest.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#180 Cherry pick #179 to release-1.0: Use logging util
  Gopkg.lock
  Gopkg.toml
  pkg/controller/controller.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/OWNERS
  vendor/github.com/kubernetes-csi/csi-lib-utils/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-lib-utils/code-of-conduct.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/.gitignore
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest/csitest.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
