Repository kubernetes-csi/external-provisioner, pull requests merged in 2018-12, with the labels that each got.

#178 Add new reserved prefixed parameter keys which are stripped out of parameter list, add deprecation notice for old keys and keep their behavior the same
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#185 Revert "Add provisioner parameters instructions to 0.4 docs"
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#191 Add msau42 to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#186 Remove provisioner argument, update README
  README.md
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#188 Don't provide access to Secrets in default RBAC
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#192 Scrub secrets 0.4
  Gopkg.lock
  Gopkg.toml
  pkg/controller/controller.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/OWNERS
  vendor/github.com/kubernetes-csi/csi-lib-utils/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-lib-utils/code-of-conduct.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/.gitignore
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi03/csi.pb.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi10/csi.pb.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest/csitest.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#193 Switch image version to canary
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#197 Fix formatting issue
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
