Repository kubernetes-csi/external-provisioner, pull requests merged in 2019-04, with the labels that each got.

#262 vendor: update to k8s.io 1.14, avoid glog
  Gopkg.lock
  Gopkg.toml
  cmd/csi-provisioner/csi-provisioner.go
  pkg/features/features.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/apiserver/pkg/util/feature/testing/feature_gate_testing.go
  vendor/k8s.io/component-base/LICENSE
  vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go
  vendor/k8s.io/component-base/cli/flag/colon_separated_multimap_string_string.go
  vendor/k8s.io/component-base/cli/flag/configuration_map.go
  vendor/k8s.io/component-base/cli/flag/flags.go
  vendor/k8s.io/component-base/cli/flag/langle_separated_map_string_string.go
  vendor/k8s.io/component-base/cli/flag/map_string_bool.go
  vendor/k8s.io/component-base/cli/flag/map_string_string.go
  vendor/k8s.io/component-base/cli/flag/namedcertkey_flag.go
  vendor/k8s.io/component-base/cli/flag/noop.go
  vendor/k8s.io/component-base/cli/flag/omitempty.go
  vendor/k8s.io/component-base/cli/flag/sectioned.go
  vendor/k8s.io/component-base/cli/flag/string_flag.go
  vendor/k8s.io/component-base/cli/flag/tristate.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#259 vendor check
  release-tools/build.make
  release-tools/travis.yml
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#261 Use leader election library from csi-lib-utils
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  deploy/kubernetes/rbac.yaml
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_386.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#263 Add Changelog for 1.1 and update README
  CHANGELOG-1.1.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#264 Update to sig-storage-lib-external-provisioner v3.0.0
  Gopkg.lock
  Gopkg.toml
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#266 Don't use external-provisioner delete finalizer
  CHANGELOG-1.1.md
  Gopkg.lock
  Gopkg.toml
  deploy/kubernetes/rbac.yaml
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#265 Prow testing
  .prow.sh
  release-tools/.prow.sh
  release-tools/README.md
  release-tools/build.make
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/util.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#268 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#267 update to Go 1.12.4
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#270 solve misleading struct deprecatedSecretParamsMap
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S
