Repository kubernetes-csi/external-provisioner, pull requests merged in 2019-05, with the labels that each got.

#273 Handle deletion of CSI migrated volumes
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#276 Cherry pick handling of deletion of CSI migrated volumes
  CHANGELOG-1.1.md
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#277 Bump provisioner lib and migration library dependencies. Update migration translation to translate the entire storage class.
  Gopkg.lock
  Gopkg.toml
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/csi-translation-lib/translate.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/volume.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, sig/storage, size/XL

#279 Add 1.2 changelog
  CHANGELOG-1.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#274 Add secret support for Provision and Delete from pvc name and namespace
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L
