Repository kubernetes-csi/external-provisioner, pull requests merged in 2019-06, with the labels that each got.

#287 [release-1.2] Add secret support for Provision and Delete from pvc name and namespace
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#282 Introduce new flag - strict-topology
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology.go
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/design, lgtm, ok-to-test, release-note, size/L

#290 Remove dummy service from the deployment
  deploy/kubernetes/deployment.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#220 Extend allowed DataSources
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#281 [release-1.0] Add secret support for Provision and Delete from pvc name and namespace
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#288 [release-1.2] Introduce new flag - strict-topology
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology.go
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/design, lgtm, ok-to-test, release-note, size/L

#286 [release-1.1] Add secret support for Provision and Delete from pvc name and namespace
  Gopkg.lock
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#292 Bump version of csi-translation-lib for CSI Migration support for Azure Disk/File, as well as backwards compatibility fixes for GCE PD
  Gopkg.lock
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/csi-translation-lib/translate.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/XL

#294 [cherry-pick] Bump version of csi-translation-lib for CSI Migration support for Azure Disk/File, as well as fixes for GCE PD
  Gopkg.lock
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/csi-translation-lib/translate.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/XL

#293 Update 1.2 changelog to follow release tools format
  CHANGELOG-1.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#296 Leader election: disable duplicate LE in provisioner lib; add lock namespacing
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#297 Cherry-pick of #296: "Leader election: disable duplicate LE in provisioner lib; add lock namespacing"
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#298 Cherrypick of #296: "Leader election: disable duplicate LE in provisioner lib; add lock namespacing"
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#299 Update 1.2 changelog
  CHANGELOG-1.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#300 Cherry-pick 1.2 changelog to release-1.2
  CHANGELOG-1.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#302 update readme with --leader-election-namespace flag
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#304 Cherry-pick #302 to release-1.2: update readme with --leader-election-namespace flag
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#303 Cherry-pick #302 to release-1.1: update readme with --leader-election-namespace flag
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#305 Add 1.3 changelog
  CHANGELOG-1.3.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M
