Repository kubernetes-csi/external-provisioner, pull requests merged in 2019-01, with the labels that each got.

#198 Remove redundant else block
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#205 Remove/Cleanup unused directory.
  examples/old/pvc.yaml
  examples/old/pvc2.yaml
  examples/old/pvc3.yaml
  examples/old/pvc4.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#207 markdown linter corrections in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#206 Correct variable declaration.
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#209 update kubernetes-sigs/sig-storage-lib-external-provisioner to fix #195
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go
  vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/volume.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#210 Add RBAC rules for CSINodeInfo
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#212 Automated cherry pick of #209: update kubernetes-sigs/sig-storage-lib-external-provisioner
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go
  vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/volume.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#215 Cache driver name
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#218 release tools
  .gitignore
  .travis.yml
  Makefile
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/build.make
  release-tools/code-of-conduct.md
  release-tools/travis.yml
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL
