Repository kubernetes-csi/external-provisioner, pull requests merged in 2019-10, with the labels that each got.

#345 Ignore non-migrated in-tree PVC when provisioning
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#349 Fix typo for leader-election-type
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#344 Ignore non-migrated in-tree PVC when provisioning
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#350 Don't process PVCs for in-tree volumes
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#351 Update sig-storage-lib-external-provisioner to v4.0.1
  Gopkg.lock
  Gopkg.toml
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/controller/volume_store.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note, size/L

#348 Record the error if we fail to get referenced storageclass and secret.
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#352 Fix claimRef and shapshotRef checks
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#353 Update 1.4 documentation
  CHANGELOG-1.4.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#354 1.3: fix Fix claimRef and snapshotRef checks
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XL

#355 1.2: Fix snapshotRef checks
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#357 1.0: Fix snapshotRef checks
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#359 Bump csi-translation-lib to HEAD
  Gopkg.lock
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/csi-translation-lib/translate.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note-none, size/L

#364 Update prow to latest release-tools
  release-tools/README.md
  release-tools/build.make
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#361 update changelog
  CHANGELOG-1.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#366 Update prow 1.2
  release-tools/README.md
  release-tools/build.make
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#362 Update changelog for v1.2.2
  CHANGELOG-1.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#365 Update prow 1.3
  release-tools/README.md
  release-tools/build.make
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#363 Add 1.0 changelog for v1.0.2
  CHANGELOG-1.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#360 Update 1.3 changelog for 1.3.1
  CHANGELOG-1.3.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#343 Unit tests for migration
  pkg/controller/controller_test.go
  pkg/controller/fake_translator_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#358 0.4: Fix snapshotRef checks
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#371 Add changelog for v0.4.3
  CHANGELOG-0.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#372 fix wrong compare expression in testcase in pkg controller
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/failing-test, lgtm, ok-to-test, release-note-none, size/XS

#327 Use csiNode informer to prevent hitting the API server for all time
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology.go
  pkg/controller/topology_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/L

#337 Use Node informer to prevent hitting the API server for all time
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology.go
  pkg/controller/topology_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#335 Update snapshot CRD to v1beta
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/pkg/client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL
