Repository kubernetes-csi/external-provisioner, pull requests merged in 2019-09, with the labels that each got.

#338 Update csi-release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#283 Need to check VolumeContentSource if creating volume from snapshot
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/L

#341 Ignore provisioning for in-tree volumes that have not been migrated
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#346 Revert "Automated cherry pick of #209: update kubernetes-sigs/sig-storage-lib-external-provisioner"
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go
  vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/volume.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#347 add 1.4 changelog
  CHANGELOG-1.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
