Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-07, with the labels that each got.

#453 master: update release-tools
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#448 Remove topology fallback logic for nodes < 1.14
  pkg/controller/controller_test.go
  pkg/controller/topology.go
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#455 Fix wrong flag name in deployment.yaml
  deploy/kubernetes/deployment.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#457 Update README with qps and burst argument description
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note, size/XS
