Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-12, with the labels that each got.

#537 Bumping csi-lib-utils to 0.9.0
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  deploy/kubernetes/deployment.yaml
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#536 avoid one GET Node per volume with late binding
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#534 Return an error when data source is unsupported
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#524 distributed provisioning
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/capacity/capacity_test.go
  pkg/capacity/mode.go
  pkg/capacity/topology/mock.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/ratelimiter.go
  pkg/controller/ratelimiter_test.go
  pkg/controller/topology.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#540 replace -capacity-controller-deployment-mode with -enable-capacity
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  pkg/capacity/mode.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note, size/M

#541 fix volume size mismatch between driver and PV
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#542 Add changelog for release v2.1.0
  CHANGELOG/CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
