Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-09, with the labels that each got.

#475 capacity: fix handling of topology changes with immediate binding SCs
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#477 capacity: fix handling of topology changes with immediate binding SCs
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#478 Add v2.0.1 release notes
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#479 optional VolumeAttachments check
  cmd/csi-provisioner/csi-provisioner.go
  deploy/kubernetes/rbac.yaml
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#480 2.0.x: optional volume attachments
  cmd/csi-provisioner/csi-provisioner.go
  deploy/kubernetes/rbac.yaml
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#482 release notes for 2.0.2
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#461 Add link to QPS and Burst documentation
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS
