Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-10, with the labels that each got.

#489 Upgrade csi-lib-utils to 0.8.1
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#490 Upgrade csi-lib-utils to 0.8.1
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#495 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#496 release-1.6: update release-tools
  go.mod
  go.sum
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#497 release-2.0: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#498 Add change log for 1.6.1 release
  CHANGELOG-1.6.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#500 Update v1.6.1 changelog
  CHANGELOG-1.6.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#502 Create v2.0.3 change log
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#503 Fix the failing multiarch builds
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#504 Cherry pick #503: Fix the failing multiarch builds
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#509 Revert to multiarch distroless base image
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#510 Update owners file
  OWNERS
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#513 upgrade azure translation lib to fix the azure file migration issue
  go.mod
  go.sum
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#516 mark Topology featuregate as GA
  pkg/features/features.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XS

#515 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#519 upgrade azure translation lib to fix the azure file migration issue
  go.mod
  go.sum
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#521 Add changelog for v2.0.4
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#518 logging: switch to klog/v2
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/topology/nodes.go
  pkg/capacity/topology/nodes_test.go
  pkg/controller/clone_controller.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/volume_store.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/util/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L
