Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-01, with the labels that each got.

#387 Use informers for StorageClasses lookups
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#392 Fix metrics typos
  README.md
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#397 Fix initialization of storageClass lister
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#398 Remove Brad Childs from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#393 issue-384, A single "default" storage class secret is added
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L
