Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-03, with the labels that each got.

#410 Add volumeMode checks to clone operations
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#423 Avoid explicit initialization of err var
  README.md
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#422 Added controller for PVC deletion
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/clone_controller.go
  pkg/controller/clone_controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#424 Reduced number of threads for finalizer removal to 1
  README.md
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, ok-to-test, release-note, size/XS
