Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-08, with the labels that each got.

#460 Bump lib-external-provisioner to v6.1.0-rc1
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#459 Add 2.0 Changelog
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-2.0.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#464 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#450 storage capacity producer
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  deploy/kubernetes/rbac.yaml
  deploy/kubernetes/storage-capacity.yaml
  go.mod
  go.sum
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/doc.go
  pkg/capacity/mode.go
  pkg/capacity/topology/doc.go
  pkg/capacity/topology/nodes.go
  pkg/capacity/topology/nodes_test.go
  pkg/capacity/topology/topology.go
  pkg/owner/owner.go
  pkg/owner/owner_test.go
  vendor/github.com/hashicorp/golang-lru/go.mod
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/ipv4/header.go
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/codec.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interfaces.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/patch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#470 Update 2.0 changelog
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#471 Bump go version to 1.15
  go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#472 Update k8s dependences to 1.19.0
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/lifecycle.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/util/net/util.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#473 Update vendor to latest snapshotter client
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v2/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotcontent.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#474 Update recommended version to 1.19
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
