Repository kubernetes-csi/external-provisioner, pull requests merged in 2020-04, with the labels that each got.

#426 Update CHANGELOG-1.1.md
  CHANGELOG-1.1.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#421 subset of supported topology keys are not working for waitforfirstconsumer
  pkg/controller/topology.go
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/M

#408 Add documentation for 1.6
  CHANGELOG-1.6.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#430 fix changelog formatting
  CHANGELOG-1.6.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#429 Correct package import and var declaration
  pkg/controller/clone_controller_test.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#427 md linter fixes
  CHANGELOG-1.1.md
  CHANGELOG-1.2.md
  CHANGELOG-1.3.md
  CHANGELOG-1.4.md
  CHANGELOG-1.5.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#402 Make leader-election flag consistent with other sidecar
  README.md
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#433 Add links to version in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#434 Start clone protection only when capability matches
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/clone_controller.go
  pkg/controller/clone_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#383 Use v1.CSINode in the external-provisioner
  .prow.sh
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/topology.go
  pkg/controller/topology_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M
