Repository kubernetes-csi/external-provisioner, pull requests merged in 2021-04, with the labels that each got.

#590 remove duplicate informer.run()
  pkg/capacity/capacity.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#601 Sanitize secrets in the requests
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#598 Add chrishenzie to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#597 Add changelog for v2.0.5
  CHANGELOG/CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#586 storage capacity: refresh after volume changes
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  deploy/kubernetes/storage-capacity.yaml
  go.mod
  go.sum
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/provision.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#583 storage capacity: object ownership
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  deploy/kubernetes/storage-capacity.yaml
  go.mod
  go.sum
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  pkg/capacity/provision.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/api-change, release-note, size/XXL

#604 Remove redundant log lines
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#606 [release-2.1] Remove redundant log lines
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#607 capacity: run tests in parallel
  pkg/capacity/capacity_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#608 [release-2.1] Add changelog for v2.1.2
  CHANGELOG/CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#610 capacity test: rebind loop variable to avoid race
  pkg/capacity/capacity_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#605 Add changelog for v2.2.0
  CHANGELOG/CHANGELOG-2.2.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#612 distributed provisioning: allowed topologies + immediate binding
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#614 Update release notes for v2.2.0
  CHANGELOG/CHANGELOG-2.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
