Repository kubernetes-csi/external-provisioner, pull requests merged in 2021-06, with the labels that each got.

#640 capacity test: create CSIStorageObject before instantiating client-set
  pkg/capacity/capacity_test.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/S

#641 release 2.2 backport
  cmd/csi-provisioner/csi-provisioner.go
  pkg/capacity/capacity_test.go
  pkg/capacity/provision.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#642 release v2.2.2
  CHANGELOG/CHANGELOG-2.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#644 Use CSI spec v1.5.0
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XL

#643 Add command line arguments to configure leader election options
  README.md
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#646 Use sig-storage-lib-external-provisioner v7.0.1
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/capacity/provision.go
  pkg/controller/clone_controller.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/k8s.io/apimachinery/pkg/util/version/version.go
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/util/doc.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/LICENSE
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/controller/controller.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/controller/doc.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/controller/metrics/doc.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/controller/metrics/metrics.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/controller/volume.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/controller/volume_store.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/util/doc.go
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v7/util/util.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XL
