Repository kubernetes-csi/external-provisioner, pull requests merged in 2021-05, with the labels that each got.

#620 Fix migration metric registration
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#621 [release-2.1] Update to k8s.io/csi-translation-lib@v0.21.0
  go.mod
  go.sum
  vendor/k8s.io/csi-translation-lib/OWNERS
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/L

#617 node topology worker should run
  cmd/csi-provisioner/csi-provisioner.go
  pkg/capacity/topology/mock.go
  pkg/capacity/topology/nodes.go
  pkg/capacity/topology/topology.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/S

#626 Release 2.2 backport
  cmd/csi-provisioner/csi-provisioner.go
  pkg/capacity/topology/mock.go
  pkg/capacity/topology/nodes.go
  pkg/capacity/topology/topology.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#627 changelog v2.2.1
  CHANGELOG/CHANGELOG-2.2.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#618 Remove dependency to k8s.io/kubernetes
  go.mod
  go.sum
  pkg/controller/topology_test.go
  vendor/k8s.io/apimachinery/pkg/api/equality/semantic.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XXL

#629 capacity: simplify topology informer
  pkg/capacity/topology/nodes.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#624 release-2.2: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#623 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#622 [release-2.0] Update to k8s.io/csi-translation-lib@v0.19.10
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/k8s.io/api/admissionregistration/v1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta2/generated.pb.go
  vendor/k8s.io/api/authentication/v1/generated.pb.go
  vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
  vendor/k8s.io/api/authorization/v1/generated.pb.go
  vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta2/generated.pb.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1beta1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/certificates/v1/generated.pb.go
  vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
  vendor/k8s.io/api/coordination/v1/generated.pb.go
  vendor/k8s.io/api/coordination/v1beta1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/discovery/v1alpha1/generated.pb.go
  vendor/k8s.io/api/discovery/v1beta1/generated.pb.go
  vendor/k8s.io/api/events/v1/generated.pb.go
  vendor/k8s.io/api/events/v1beta1/generated.pb.go
  vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/generated.pb.go
  vendor/k8s.io/api/networking/v1/generated.pb.go
  vendor/k8s.io/api/networking/v1beta1/generated.pb.go
  vendor/k8s.io/api/node/v1alpha1/generated.pb.go
  vendor/k8s.io/api/node/v1beta1/generated.pb.go
  vendor/k8s.io/api/policy/v1beta1/generated.pb.go
  vendor/k8s.io/api/rbac/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
  vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
  vendor/k8s.io/api/settings/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1/generated.pb.go
  vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XXL

#636 Fix env name from POD_NAMESPACE to NAMESPACE for capacity-ownerref-level option
  cmd/csi-provisioner/csi-provisioner.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-ok-to-test, release-note, size/XS

#634 release-2.2: update release-tools + OWNERS
  OWNERS
  OWNERS_ALIASES
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/OWNERS
  release-tools/OWNERS_ALIASES
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#633 master: update release-tools + OWNERS
  OWNERS
  OWNERS_ALIASES
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/OWNERS
  release-tools/OWNERS_ALIASES
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#635 Add SupportsBlock method to provisionWrapper for being able to use block device
  pkg/capacity/provision.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/S
