Repository kubernetes-csi/external-provisioner, pull requests merged in 2021-03, with the labels that each got.

#571 [release-2.1] Update to k8s.io/csi-translation-lib@v0.20.4
  go.mod
  go.sum
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/L

#580 cherrypick csi-translation-lib fix
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#578 release v2.1.1
  CHANGELOG/CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#581 Fix version in release notes
  CHANGELOG/CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#532 doc: UML diagram for volume creation and deletion
  Makefile
  README.md
  doc/design.md
  doc/doc.make
  doc/provisioning.png
  doc/provisioning.puml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#567 Add TranslateInTreeStorageClassToCSI in Delete
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/M

#594 master: update release-tools
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#575 Update README.md where function name is incorrect
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#579 additional metrics
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/workqueue/metrics.go
  vendor/k8s.io/component-base/metrics/testutil/metrics.go
  vendor/k8s.io/component-base/metrics/testutil/promlint.go
  vendor/k8s.io/component-base/metrics/testutil/testutil.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL
