Repository kubernetes-csi/external-provisioner, pull requests merged in 2021-02, with the labels that each got.

#555 master: update release-tools
  release-tools/README.md
  release-tools/boilerplate/boilerplate.py
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#564 update sig-storage-lib-external-provisioner to v6.3.0
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#560 feat: Add migrated label to metrics
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#566 Upgrade csi-translation-lib dependency
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
  vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
  vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
  vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
  vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XL

#565 Capacity informer race
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#568 Release 2.1: capacity informer race
  pkg/capacity/capacity.go
  pkg/capacity/capacity_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M
