Repository kubernetes-csi/external-provisioner, pull requests merged in 2021-08, with the labels that each got.

#659 Skip K8S 1.19 jobs
  .prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#660 Update k8s dependencies to v1.22.0
  README.md
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/k8s.io/csi-translation-lib/go.mod
  vendor/k8s.io/csi-translation-lib/go.sum
  vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, sig/storage, size/L

#650 Update external-snapshotter client version to v4.1.0
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XXL

#630 Map PV access modes to CSI access modes based on driver capability
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/accessmodes/access_modes.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#651 Fix data race in cloning protection controller
  pkg/controller/clone_controller.go
Labels: kind/bug, cncf-cla: yes, approved, size/XS, lgtm, release-note, ok-to-test

#469 Set READONLY flag in CSI PV based on PVC accessmode
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note

#664 Clean up .travis.yml
  .travis.yml
  README.md
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none, ok-to-test

#666 Update snapshot support level in the readme to GA from beta
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, release-note-none

#665 Add changelog for v3.0.0
  CHANGELOG/CHANGELOG-3.0.md
  README.md
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/documentation, release-note-none

#663 Clean up unused vars and types
  pkg/controller/controller.go
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none, ok-to-test
