Repository kubernetes-csi/external-provisioner, pull requests merged in 2022-12, with the labels that each got.

#834 Update dependency go modules for k8s v1.26.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note-none

#844 Upgrade csi-lib-utils to v0.12.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, approved, kind/cleanup, lgtm, release-note-none

#838 Add changelog for v3.4.0
  CHANGELOG/CHANGELOG-3.4.md
  README.md
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/documentation, release-note-none
