Repository kubernetes-csi/external-provisioner, pull requests merged in 2023-09, with the labels that each got.

#1022 Add changelog for v3.6
  CHANGELOG/CHANGELOG-3.6.md
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/documentation, release-note-none

#1023 update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/S

#1029 Adjust groups in dependabot
  .github/dependabot.yaml
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none
