Repository kubernetes-csi/external-provisioner, pull requests merged in 2023-12, with the labels that each got.

#1129 Update release tools to fix broken image build pipeline
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-modules-update.sh
  release-tools/prow.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note-none

#1126 Enable prevent-volume-mode-conversion by default following k8s 1.28 release
  README.md
  cmd/csi-provisioner/csi-provisioner.go
Labels: kind/feature, cncf-cla: yes, approved, size/XS, lgtm, release-note-action-required, ok-to-test

#1132 CVE-2023-48795: bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note

#1133 Update dependency go modules for k8s v1.29.0
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/kubernetes/pkg/apis/batch/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note

#1135 Update csi-lib-utils to v0.17.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, size/M, lgtm, release-note-none

#1138 Update go modules
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/S

#1139 Changelog for v3.6.3
  CHANGELOG/CHANGELOG-3.6.md
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/S
