Repository kubernetes-csi/external-provisioner, pull requests merged in 2023-08, with the labels that each got.

#960 Release tools update
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
  release-tools/contrib/get_supported_version_csi-sidecar.py
  release-tools/prow.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note-none

#963 Enable dependabot for all dependencies
  .github/dependabot.yaml
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none

#990 Enable dependabot raising PR by groups
  .github/dependabot.yaml
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, release-note-none, size/S

#1003 Enable dependabot Beta Features
  .github/dependabot.yaml
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none

#1013 Group the rest of dependencies in dependabot
  .github/dependabot.yaml
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none

#999 Update dependency go modules for k8s v1.28.0
  go.mod
  go.sum
  release-tools/prow.sh
  vendor/k8s.io/api/apidiscovery/v2beta1/generated.proto
  vendor/k8s.io/api/apidiscovery/v2beta1/types.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/endpoints/installer.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/client-go/applyconfigurations/core/v1/loadbalanceringress.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/kubernetes/pkg/api/service/warnings.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/defaults.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, approved, lgtm, release-note-none, ok-to-test
