Repository kubernetes-csi/external-provisioner, pull requests merged in 2023-04, with the labels that each got.

#905 Update sig-storage-lib-external-provisioner to v8.0.1
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go
Labels: kind/bug, cncf-cla: yes, approved, size/M, lgtm, release-note

#906 Update sig-storage-lib-external-provisioner to v8.0.1
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go
Labels: kind/bug, cncf-cla: yes, approved, size/M, lgtm, release-note

#907 Update sig-storage-lib-external-provisioner to v8.0.1
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go
Labels: kind/bug, cncf-cla: yes, approved, size/M, lgtm, release-note

#909 Add changelog for v3.2.2
  CHANGELOG/CHANGELOG-3.2.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, release-note-none

#910 Add changelog for v3.4.1
  CHANGELOG/CHANGELOG-3.4.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, release-note-none

#911 Add changelog for v3.3.1
  CHANGELOG/CHANGELOG-3.3.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, release-note-none

#919 Add changelog for 3.5.0
  CHANGELOG/CHANGELOG-3.5.md
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/documentation, release-note-none

#920 Update csi-release tools
  release-tools/cloudbuild.yaml
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none

#921 Update csi release tools
  release-tools/build.make
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-none

#922 Update feature status for 1.27
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, kind/documentation, release-note-none
