Repository kubernetes-csi/external-provisioner, pull requests merged in 2024-08, with the labels that each got.

#1250 Update lib-external-provisioner to v10.0.1
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v10/controller/controller.go
Labels: kind/bug, cncf-cla: yes, approved, size/M, lgtm, release-note

#1251 Manual cherry pick of #1250: Update lib-external-provisioner to v10.0.1
  go.mod
  go.sum
  pkg/controller/controller_test.go
  release-tools/.github/dependabot.yaml
  release-tools/.github/workflows/codespell.yml
  release-tools/.github/workflows/trivy.yaml
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/generate-patch-release-notes.sh
  release-tools/prow.sh
  vendor/modules.txt
  vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v10/controller/controller.go
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note

#1252 Add changelog for v5.0.2
  CHANGELOG/CHANGELOG-5.0.md
Labels: cncf-cla: yes, approved, lgtm, kind/documentation, release-note-none, size/S

#1256 Update Kubernetes to v1.31.0
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
Labels: cncf-cla: yes, approved, size/XL, kind/cleanup, lgtm, release-note, ok-to-test

#1253 Promote VolumeAttributesClass to Beta
  README.md
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/features/features.go
Labels: cncf-cla: yes, approved, lgtm, kind/documentation, release-note, size/S

#1264 Add changelog for v5.1.0
  CHANGELOG/CHANGELOG-5.1.md
  README.md
Labels: cncf-cla: yes, approved, lgtm

#1267 fix data race on makeCapacity & fakeController
  pkg/capacity/capacity_test.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, release-note-none, size/S, ok-to-test
