Repository kubernetes-csi/external-provisioner, pull requests merged in 2024-04, with the labels that each got.

#1190 Fix clone controller shallow copy bug
  pkg/controller/clone_controller.go
  pkg/controller/controller.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, release-note, size/S, ok-to-test

#1200 Update README.md: Add to new csi-driver docs
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, kind/documentation, release-note-none, ok-to-test

#1193 fix: don't pass confusing value to GetCapacityRequest.VolumeCapabilities
  pkg/capacity/capacity.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, release-note, size/S, ok-to-test

#1196 feat: support PVC annotation template for provisioner secret
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, release-note, size/S, ok-to-test

#1155 add patch verb for persistentvolumes resources in the external-provisioner-runner clusterrole
  deploy/kubernetes/rbac.yaml
Labels: kind/bug, cncf-cla: yes, approved, size/XS, lgtm, release-note
