Repository kubernetes-csi/external-provisioner, pull requests merged in 2024-05, with the labels that each got.

#1209 promote HonorReclaimPolicy to beta
  README.md
  pkg/features/features.go
Labels: kind/feature, cncf-cla: yes, approved, size/XS, lgtm, release-note

#1167 set Topology feature gate default to true
  pkg/features/features.go
Labels: cncf-cla: yes, approved, size/XS, kind/cleanup, lgtm, release-note-action-required, ok-to-test

#1216 Add changelog for v5.0
  CHANGELOG/CHANGELOG-5.0.md
  README.md
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/documentation, release-note-none

#1218 Promote CSINodeExpandSecret to GA
  README.md
  pkg/controller/controller_test.go
  release-tools/.github/dependabot.yaml
  release-tools/.github/workflows/codespell.yml
  release-tools/.github/workflows/trivy.yaml
  release-tools/SIDECAR_RELEASE_PROCESS.md
Labels: cncf-cla: yes, approved, size/M, lgtm, release-note-none
