Repository kubernetes-csi/external-provisioner, pull requests merged in 2024-09, with the labels that each got.

#1269 Fix race in tests
  pkg/controller/clone_controller_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, release-note-none

#1271 Use protobuf encoding for core K8s APIs in external-provisioner
  cmd/csi-provisioner/csi-provisioner.go
Labels: kind/feature, cncf-cla: yes, approved, size/XS, lgtm, release-note-none, ok-to-test

#1262 Bump CSI spec 1.10
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/topology_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/driver-controller.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/driver.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/driver.mock.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/mock.go
  vendor/github.com/kubernetes-csi/csi-test/v5/utils/protobuf_matcher.go
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/testing/protocmp/reflect.go
  vendor/google.golang.org/protobuf/testing/protocmp/util.go
  vendor/google.golang.org/protobuf/testing/protocmp/xform.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/XXL, approved, kind/cleanup, lgtm, release-note
