Repository kubernetes-csi/external-provisioner, pull requests merged in 2025-05, with the labels that each got.

#1371 External provisioner csi tool update
  release-tools/prow.sh
Labels: cncf-cla: yes, approved, lgtm, release-note-none, size/S, ok-to-test

#1379 Add `-automaxprocs` flag for configuring `GOMAXPROCS`
  README.md
  cmd/csi-provisioner/csi-provisioner.go
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/standardflags/automaxprocs.go
  vendor/modules.txt
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, release-note

#1383 Add changelog for 5.3
  CHANGELOG/CHANGELOG-5.3.md
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/documentation, release-note-none
